---
flighdeck_motd_name: zookeeper 3.7

flightdeck_groups:
  - name: "zookeeper"

flightdeck_users:
  - name: "zookeeper"
    group: "zookeeper"
    home: "/home/zookeeper"

flightdeck_root_prompt: '\u@flightdeck-zookeeper-3.7:\w# '
flightdeck_user_prompt: '\u@flightdeck-zookeeper-3.7:\w$ '

flightdeck_motd_links:
  - name: 'Code & docs'
    url: 'https://github.com/ten7/flightdeck-zookeeper-3.7'
  - name: ' Learn more'
    url: 'https://flightdeck.ten7.com/'

flightdeck_init_commands: |
  if [ -n "${FLIGHTDECK_CONFIG}" ]; then
    config_file=$(mktemp "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
    echo "$FLIGHTDECK_CONFIG" | base64 -d > $config_file
    ansible-playbook -i /ansible/inventories/all.ini -e "@${config_file}" /ansible/init.yml
  elif [ -f "${FLIGHTDECK_CONFIG_FILE}" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@${FLIGHTDECK_CONFIG_FILE}" /ansible/init.yml
  elif [ -f "/config/zookeeper/flightdeck-zookeeper.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/zookeeper/flightdeck-zookeeper.yml" /ansible/init.yml
  elif [ -f "/config/zookeeper/flight-deck-zookeeper.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/zookeeper/flight-deck-zookeeper.yml" /ansible/init.yml
  else
    ansible-playbook -i /ansible/inventories/all.ini /ansible/init.yml
  fi

flightdeck_run_commands: |
  if [ -n "${FLIGHTDECK_CONFIG}" ]; then
    config_file=$(mktemp "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
    echo "$FLIGHTDECK_CONFIG" | base64 -d > $config_file
    ansible-playbook -i /ansible/inventories/all.ini -e "@${config_file}" /ansible/run.yml
  elif [ -f "${FLIGHTDECK_CONFIG_FILE}" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@${FLIGHTDECK_CONFIG_FILE}" /ansible/run.yml
  elif [ -f "/config/zookeeper/flightdeck-zookeeper.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/zookeeper/flightdeck-zookeeper.yml" /ansible/run.yml
  elif [ -f "/config/zookeeper/flight-deck-zookeeper.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/zookeeper/flight-deck-zookeeper.yml" /ansible/run.yml
  else
    ansible-playbook -i /ansible/inventories/all.ini /ansible/run.yml
  fi

flightdeck_path:
  - '/opt/zookeeper/bin'

flightdeck_zookeeper_defaults:
  tickTime: "1000"
  dataDir: "/data"
  clientPort: "2181"
  initLimit: "120"
  syncLimit: "120"
  myIdFromHostname: true
  servers: []
  autopurge:
    state: yes
    snapRetainCount: 3
    purgeInterval: 24

flightdeck_zookeeper: "{{ flightdeck_zookeeper_defaults }}"
