---
- hosts: zookeeper
  roles:
    - ten7.flightdeck_base
  tasks:
    - name: Install from apk.
      apk:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - "openjdk11-jre"
        - "curl"
        - "tar"
        - "rsync"
        - "lsof"
      notify:
        - clear apk cache
    - name: Create a temp directory to store files needed by the run
      tempfile:
        state: directory
        prefix: "ansible-deploy-"
      register: _run_temp_dir
      notify:
        - delete temp items
    - name: Download zookeeper
      get_url:
        url: "https://dlcdn.apache.org/zookeeper/zookeeper-3.7.0/apache-zookeeper-3.7.0-bin.tar.gz"
        dest: "{{ _run_temp_dir.path }}/zookeeper.tar.gz"
        checksum: "sha512:64e2701c019ed46f45f4d53b2c5eaeaf7cf48c342bbafa032a0819d527fc77caebfada6bdad34e5171e6d838f40b16c95b62ce378b53dfc827af2d60cec0b17c"
        mode: "u=rwx,g=rwx,o="
    - name: Ensure key directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "zookeeper"
        group: "zookeeper"
        mode: "u=rwx,g=rwx,o=r"
        recurse: yes
      loop:
        - "/opt"
        - "/data"
        - "{{ _run_temp_dir.path }}/zookeeper"
    - name: Expand archive
      unarchive:
        src: "{{ _run_temp_dir.path }}/zookeeper.tar.gz"
        dest: "{{ _run_temp_dir.path }}/zookeeper"
        owner: "zookeeper"
        group: "zookeeper"
        mode: "u=rwx,g=rwx,o=r"
        extra_opts:
          - "--strip-components=1"
    - name: Move the zookeeper directory to /opt
      command: >
        mv {{ _run_temp_dir.path }}/zookeeper /opt
    - name: Remove unnecessary files from zookeeper install
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/opt/zookeeper/docs"
    - name: Create the log directory
      file:
        path: "/opt/zookeeper/server/logs"
        state: directory
        owner: "zookeeper"
        group: "zookeeper"
        mode: "u=rwx,g=rwx,o="
    # Deploy the run command at build time using defaults in the template.
    # This way, the container can still run via FLIGHTDECK_SKIP_ENTRYPOINT.
    - name: Deploy key scripts.
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "zookeeper"
        group: "zookeeper"
        mode: "u=rwx,g=rwx,o="
      loop:
        - src: "templates/zookeeper-foreground.sh.j2"
          dest: "/opt/zookeeper/bin/zookeeper-foreground.sh"
  handlers:
    - name: delete temp items
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ _run_temp_dir.path }}"
    - name: clear apk cache
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/*"
        - "/var/cache/apk/*"
